// <auto-generated />
using System;
using Joylet.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Joylet.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220129012918_LevelTwoDiscount")]
    partial class LevelTwoDiscount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Joylet.API.Domain.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasPrecision(10, 2)
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Name = "ketchup",
                            Price = 999m
                        },
                        new
                        {
                            Id = 6,
                            Name = "mayonnaise",
                            Price = 999m
                        },
                        new
                        {
                            Id = 7,
                            Name = "fries",
                            Price = 378m
                        },
                        new
                        {
                            Id = 8,
                            Name = "ham",
                            Price = 147m
                        });
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CartDetails")
                        .HasColumnType("longtext");

                 //   b.Property<int?>("DeliveryFeesId")
                  //      .HasColumnType("int");

                    b.HasKey("Id");

               //     b.HasIndex("DeliveryFeesId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.CartItem", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("CartsItems");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            CartId = 1,
                            Quantity = 6
                        },
                        new
                        {
                            ArticleId = 2,
                            CartId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            ArticleId = 4,
                            CartId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ArticleId = 2,
                            CartId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            ArticleId = 3,
                            CartId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            ArticleId = 5,
                            CartId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            ArticleId = 6,
                            CartId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            ArticleId = 7,
                            CartId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            ArticleId = 8,
                            CartId = 5,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.DeliveryFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryFees");
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 2,
                            IsActive = true,
                            IsExpired = false,
                            Type = "amount",
                            Value = 25m
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 5,
                            IsActive = true,
                            IsExpired = false,
                            Type = "percentage",
                            Value = 30m
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 6,
                            IsActive = true,
                            IsExpired = false,
                            Type = "percentage",
                            Value = 30m
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 7,
                            IsActive = true,
                            IsExpired = false,
                            Type = "percentage",
                            Value = 25m
                        },
                        new
                        {
                            Id = 5,
                            ArticleId = 8,
                            IsActive = true,
                            IsExpired = false,
                            Type = "percentage",
                            Value = 10m
                        });
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.Cart", b =>
                {
                    //b.HasOne("Joylet.API.Domain.Models.DeliveryFee", "DeliveryFees")
                    //    .WithMany()
                    //    .HasForeignKey("DeliveryFeesId");

                    //b.Navigation("DeliveryFees");
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.CartItem", b =>
                {
                    b.HasOne("Joylet.API.Domain.Models.Article", "Articles")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joylet.API.Domain.Models.Cart", "Carts")
                        .WithMany("CartsItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articles");

                    b.Navigation("Carts");
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.Discount", b =>
                {
                    b.HasOne("Joylet.API.Domain.Models.Article", "Articles")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.Cart", b =>
                {
                    b.Navigation("CartsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
