// <auto-generated />
using Joylet.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Joylet.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220121202511_InitialLevelOne")]
    partial class InitialLevelOne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Joylet.API.Domain.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasPrecision(10, 2)
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "water",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Name = "honey",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3,
                            Name = "mango",
                            Price = 400m
                        },
                        new
                        {
                            Id = 4,
                            Name = "tea",
                            Price = 1000m
                        });
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CartDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartDetails = "Details 1"
                        },
                        new
                        {
                            Id = 2,
                            CartDetails = "Details 2"
                        },
                        new
                        {
                            Id = 3,
                            CartDetails = "Details 3"
                        });
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.CartItem", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("CartsItems");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            CartId = 1,
                            Quantity = 6
                        },
                        new
                        {
                            ArticleId = 2,
                            CartId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            ArticleId = 4,
                            CartId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ArticleId = 2,
                            CartId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            ArticleId = 3,
                            CartId = 2,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.CartItem", b =>
                {
                    b.HasOne("Joylet.API.Domain.Models.Article", "Articles")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joylet.API.Domain.Models.Cart", "Carts")
                        .WithMany("CartsItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articles");

                    b.Navigation("Carts");
                });

            modelBuilder.Entity("Joylet.API.Domain.Models.Cart", b =>
                {
                    b.Navigation("CartsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
